package entities;

public enum POSTags {
	
		COORDINATINGCONJUCTION("CC"),	
		CARDINALNUMBER("CD"),
		DETERMINER("DT"),	
		EXISTENTIAL("EX"),	
		FOREIGNWORK("FW"),	
		PREPOSITIONCONJUNCTION("IN"),
		ADJECTIVE("JJ"),
		COMPARATIVEADJECTIVE("JJR"),	
		ADJECTIVESUPERLATIVE("JJS"),	
		LISTITEM("LS"),
		MODAL("MD"),	
		NOUN("NN"), 
		PLURALNOUN("NNS"),	
		SINGULARNOUN("NNP"),
		PROPERNOUN("NNPS"),	
		PREDETERMINER("PDT"),	
		POSSESIVEENDING("POS"),	
		PERSONALPRONOUN("PRP"),	
		POSSESSIVEPRONOUND("PRP$"),	
		ADVERB("RB"),	
		ADVERBCOMPARATIVE("RBR"),
		ADVERBSUPERLATIVE("RBS"),
		PARTICLE("RP"),
		SYMBOL("SYM"),
		TO("TO"),
		INTERJECTION("UH"),	
		VERBBASEFORM("VB"),
		VERBPASTTENSE("VBD"),	
		PRONOUNCE("WP");
	
	private String tags;
	
	private POSTags (String tag){
		this.tags = tag;
	}

}
